### PR TITLE
Fix #2

### LINKED ISSUE #2: namcap errors about missing libraries
Errors when running [namcap](https://wiki.archlinux.org/index.php/Creating_packages#Checking_package_sanity) on the built packages

```sh
namcap libnvidia-container-1.0.0-1-x86_64.pkg.tar

libnvidia-container E: Dependency libelf detected and not included (libraries ['usr/lib/libelf.so.1'] needed in files ['usr/lib/libnvidia-container.so.1.0.0'])
```

```sh
namcap libnvidia-container-tools-1.0.0-1-x86_64.pkg.tar

libnvidia-container-tools E: Dependency libtirpc detected and not included (libraries ['usr/lib/libtirpc.so.3'] needed in files ['usr/bin/nvidia-container-cli'])
```

Probably because specific versions of `libelf` and `libtirpc` were used but not included in the packages?
I don't have this problem with `libnvidia-container-bin` and `libnvidia-container-tools-bin` which use the rpm packages. Let me check how they did it.

### PR DESCRIPTION
**Pull request by kiendang**
Fix #2

### CODE REVIEW

**Comment by kiendang** [comment]
The first commit fixes the namcap warning.

**Comment by julie-is-late** [comment]
looks good. I was messing around w/ this yesterday but couldn't quite get the flag ordering right, nice job figuring that out though. 

Hopefully this means we can push all of these in the near future :)

**Comment by kiendang** [comment]
Yup. I tested all the packages locally today and everything seems to work. Just need to settle kiendang/aur-nvidia-container-runtime-bin#1 and we're good to go.

**Comment by julie-is-late** [comment]
Nice. yeah I was messing with it yesterday and from the debug logs looked
like everything was working.
I forgot to update all of the srcinfo's when I changed the licenses though
so let me do that now.

**Comment by kiendang** [comment]
Ah no worries I updated them already.

**Comment by julie-is-late** [comment]
Oh cool, thanks. One of these days I'll stop forgetting them... :upside_down_face:

**Pull request merged**
